// Generated by eapi (DO NOT EDIT)
#include "eapi_drv.h"
#include "libusb.h"
#include "libusb_drv.h"

int e_struct_libusb_device_descriptor(eapi_ctx_t* ctx, cbuf_t* c_out, struct libusb_device_descriptor *ptr)
{
  cbuf_put_tuple_begin(c_out,15);
  cbuf_put_atom(c_out,"libusb_device_descriptor");
  cbuf_put_uint8(c_out,ptr->bLength);
  cbuf_put_uint8(c_out,ptr->bDescriptorType);
  cbuf_put_uint16(c_out,ptr->bcdUSB);
  cbuf_put_uint8(c_out,ptr->bDeviceClass);
  cbuf_put_uint8(c_out,ptr->bDeviceSubClass);
  cbuf_put_uint8(c_out,ptr->bDeviceProtocol);
  cbuf_put_uint8(c_out,ptr->bMaxPacketSize0);
  cbuf_put_uint16(c_out,ptr->idVendor);
  cbuf_put_uint16(c_out,ptr->idProduct);
  cbuf_put_uint16(c_out,ptr->bcdDevice);
  cbuf_put_uint8(c_out,ptr->iManufacturer);
  cbuf_put_uint8(c_out,ptr->iProduct);
  cbuf_put_uint8(c_out,ptr->iSerialNumber);
  cbuf_put_uint8(c_out,ptr->bNumConfigurations);
  cbuf_put_tuple_end(c_out,15);
  return 0;
}

int e_struct_libusb_endpoint_descriptor(eapi_ctx_t* ctx, cbuf_t* c_out, struct libusb_endpoint_descriptor *ptr)
{
  cbuf_put_tuple_begin(c_out,11);
  cbuf_put_atom(c_out,"libusb_endpoint_descriptor");
  cbuf_put_uint8(c_out,ptr->bLength);
  cbuf_put_uint8(c_out,ptr->bDescriptorType);
  cbuf_put_uint8(c_out,ptr->bEndpointAddress);
  cbuf_put_uint8(c_out,ptr->bmAttributes);
  cbuf_put_uint16(c_out,ptr->wMaxPacketSize);
  cbuf_put_uint8(c_out,ptr->bInterval);
  cbuf_put_uint8(c_out,ptr->bRefresh);
  cbuf_put_uint8(c_out,ptr->bSynchAddress);
  cbuf_put_binary(c_out,ptr->extra,ptr->extra_length);
  cbuf_put_int(c_out,ptr->extra_length);
  cbuf_put_tuple_end(c_out,11);
  return 0;
}

int e_struct_libusb_interface_descriptor(eapi_ctx_t* ctx, cbuf_t* c_out, struct libusb_interface_descriptor *ptr)
{
  cbuf_put_tuple_begin(c_out,13);
  cbuf_put_atom(c_out,"libusb_interface_descriptor");
  cbuf_put_uint8(c_out,ptr->bLength);
  cbuf_put_uint8(c_out,ptr->bDescriptorType);
  cbuf_put_uint8(c_out,ptr->bInterfaceNumber);
  cbuf_put_uint8(c_out,ptr->bAlternateSetting);
  cbuf_put_uint8(c_out,ptr->bNumEndpoints);
  cbuf_put_uint8(c_out,ptr->bInterfaceClass);
  cbuf_put_uint8(c_out,ptr->bInterfaceSubClass);
  cbuf_put_uint8(c_out,ptr->bInterfaceProtocol);
  cbuf_put_uint8(c_out,ptr->iInterface);
  cbuf_put_list_begin(c_out,ptr->bNumEndpoints);
  { 
     int _lst_i;
     for (_lst_i = 0; _lst_i < ptr->bNumEndpoints; _lst_i++) {
      e_struct_libusb_endpoint_descriptor(ctx,c_out,&ptr->endpoint[_lst_i]);
    }
  }
cbuf_put_list_end(c_out,ptr->bNumEndpoints);
;
  cbuf_put_binary(c_out,ptr->extra,ptr->extra_length);
  cbuf_put_int(c_out,ptr->extra_length);
  cbuf_put_tuple_end(c_out,13);
  return 0;
}

int e_struct_libusb_interface(eapi_ctx_t* ctx, cbuf_t* c_out, struct libusb_interface *ptr)
{
  cbuf_put_tuple_begin(c_out,3);
  cbuf_put_atom(c_out,"libusb_interface");
  cbuf_put_list_begin(c_out,ptr->num_altsetting);
  { 
     int _lst_i;
     for (_lst_i = 0; _lst_i < ptr->num_altsetting; _lst_i++) {
      e_struct_libusb_interface_descriptor(ctx,c_out,&ptr->altsetting[_lst_i]);
    }
  }
cbuf_put_list_end(c_out,ptr->num_altsetting);
;
  cbuf_put_int(c_out,ptr->num_altsetting);
  cbuf_put_tuple_end(c_out,3);
  return 0;
}

int e_struct_libusb_config_descriptor(eapi_ctx_t* ctx, cbuf_t* c_out, struct libusb_config_descriptor *ptr)
{
  cbuf_put_tuple_begin(c_out,12);
  cbuf_put_atom(c_out,"libusb_config_descriptor");
  cbuf_put_uint8(c_out,ptr->bLength);
  cbuf_put_uint8(c_out,ptr->bDescriptorType);
  cbuf_put_uint16(c_out,ptr->wTotalLength);
  cbuf_put_uint8(c_out,ptr->bNumInterfaces);
  cbuf_put_uint8(c_out,ptr->bConfigurationValue);
  cbuf_put_uint8(c_out,ptr->iConfiguration);
  cbuf_put_uint8(c_out,ptr->bmAttributes);
  cbuf_put_uint8(c_out,ptr->MaxPower);
  cbuf_put_list_begin(c_out,ptr->bNumInterfaces);
  { 
     int _lst_i;
     for (_lst_i = 0; _lst_i < ptr->bNumInterfaces; _lst_i++) {
      e_struct_libusb_interface(ctx,c_out,&ptr->interface[_lst_i]);
    }
  }
cbuf_put_list_end(c_out,ptr->bNumInterfaces);
;
  cbuf_put_binary(c_out,ptr->extra,ptr->extra_length);
  cbuf_put_int(c_out,ptr->extra_length);
  cbuf_put_tuple_end(c_out,12);
  return 0;
}

int eapi_dispatch(eapi_ctx_t* ctx, unsigned int cmd, cbuf_t* c_in, cbuf_t* c_out)
{
  switch(cmd) {
  case LIBUSB_DRV_CMD_SET_DEBUG: {
    int level;
    cbuf_get_int(c_in,&level);
    libusb_drv_impl_set_debug(ctx,c_out,level);
    break;
  }
  case LIBUSB_DRV_CMD_GET_DEVICE_LIST: {
    libusb_drv_impl_get_device_list(ctx,c_out);
    break;
  }
  case LIBUSB_DRV_CMD_GET_CONFIGURATION: {
    libusb_device_handle* dev_handle;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    libusb_drv_impl_get_configuration(ctx,c_out,dev_handle);
    break;
  }
  case LIBUSB_DRV_CMD_GET_DEVICE_DESCRIPTOR: {
    libusb_device* dev;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    libusb_drv_impl_get_device_descriptor(ctx,c_out,dev);
    break;
  }
  case LIBUSB_DRV_CMD_GET_ACTIVE_CONFIG_DESCRIPTOR: {
    libusb_device* dev;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    libusb_drv_impl_get_active_config_descriptor(ctx,c_out,dev);
    break;
  }
  case LIBUSB_DRV_CMD_GET_CONFIG_DESCRIPTOR: {
    libusb_device* dev;
    uint8_t config_index;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    cbuf_get_uint8(c_in,&config_index);
    libusb_drv_impl_get_config_descriptor(ctx,c_out,dev,config_index);
    break;
  }
  case LIBUSB_DRV_CMD_GET_CONFIG_DESCRIPTOR_BY_VALUE: {
    libusb_device* dev;
    uint8_t configurationValue;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    cbuf_get_uint8(c_in,&configurationValue);
    libusb_drv_impl_get_config_descriptor_by_value(ctx,c_out,dev,configurationValue);
    break;
  }
  case LIBUSB_DRV_CMD_GET_BUS_NUMBER: {
    libusb_device* dev;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    libusb_drv_impl_get_bus_number(ctx,c_out,dev);
    break;
  }
  case LIBUSB_DRV_CMD_GET_DEVICE_ADDRESS: {
    libusb_device* dev;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    libusb_drv_impl_get_device_address(ctx,c_out,dev);
    break;
  }
  case LIBUSB_DRV_CMD_GET_MAX_PACKET_SIZE: {
    libusb_device* dev;
    uint8_t endPoint;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    cbuf_get_uint8(c_in,&endPoint);
    libusb_drv_impl_get_max_packet_size(ctx,c_out,dev,endPoint);
    break;
  }
  case LIBUSB_DRV_CMD_GET_MAX_ISO_PACKET_SIZE: {
    libusb_device* dev;
    uint8_t endPoint;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    cbuf_get_uint8(c_in,&endPoint);
    libusb_drv_impl_get_max_iso_packet_size(ctx,c_out,dev,endPoint);
    break;
  }
  case LIBUSB_DRV_CMD_OPEN: {
    libusb_device* dev;
    eapi_get_pointer(ctx,c_in, (void**)&dev);
    libusb_drv_impl_open(ctx,c_out,dev);
    break;
  }
  case LIBUSB_DRV_CMD_CLOSE: {
    libusb_device_handle* dev_handle;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    libusb_drv_impl_close(ctx,c_out,dev_handle);
    break;
  }
  case LIBUSB_DRV_CMD_SET_CONFIGURATION: {
    libusb_device_handle* dev_handle;
    int configuration;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_int(c_in,&configuration);
    libusb_drv_impl_set_configuration(ctx,c_out,dev_handle,configuration);
    break;
  }
  case LIBUSB_DRV_CMD_CLAIM_INTERFACE: {
    libusb_device_handle* dev_handle;
    int iface;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_int(c_in,&iface);
    libusb_drv_impl_claim_interface(ctx,c_out,dev_handle,iface);
    break;
  }
  case LIBUSB_DRV_CMD_RELEASE_INTERFACE: {
    libusb_device_handle* dev_handle;
    int iface;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_int(c_in,&iface);
    libusb_drv_impl_release_interface(ctx,c_out,dev_handle,iface);
    break;
  }
  case LIBUSB_DRV_CMD_OPEN_DEVICE_WITH_VID_PID: {
    uint16_t vendor_id;
    uint16_t product_id;
    cbuf_get_uint16(c_in,&vendor_id);
    cbuf_get_uint16(c_in,&product_id);
    libusb_drv_impl_open_device_with_vid_pid(ctx,c_out,vendor_id,product_id);
    break;
  }
  case LIBUSB_DRV_CMD_SET_INTERFACE_ALT_SETTING: {
    libusb_device_handle* dev_handle;
    int interface_number;
    int alternate_setting;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_int(c_in,&interface_number);
    cbuf_get_int(c_in,&alternate_setting);
    libusb_drv_impl_set_interface_alt_setting(ctx,c_out,dev_handle,interface_number,alternate_setting);
    break;
  }
  case LIBUSB_DRV_CMD_CLEAR_HALT: {
    libusb_device_handle* dev_handle;
    int endpoint;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_int(c_in,&endpoint);
    libusb_drv_impl_clear_halt(ctx,c_out,dev_handle,endpoint);
    break;
  }
  case LIBUSB_DRV_CMD_RESET_DEVICE: {
    libusb_device_handle* dev_handle;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    libusb_drv_impl_reset_device(ctx,c_out,dev_handle);
    break;
  }
  case LIBUSB_DRV_CMD_CONTROL_TRANSFER_WRITE: {
    libusb_device_handle* dev_handle;
    uint8_t request_type;
    uint8_t request;
    uint16_t value;
    uint16_t index;
    eapi_binary_t data;
    unsigned int timeout;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_uint8(c_in,&request_type);
    cbuf_get_uint8(c_in,&request);
    cbuf_get_uint16(c_in,&value);
    cbuf_get_uint16(c_in,&index);
    cbuf_get_nbinary(c_in,&data);
    cbuf_get_uint(c_in,&timeout);
    libusb_drv_impl_control_transfer_write(ctx,c_out,dev_handle,request_type,request,value,index,&data,timeout);
    cbuf_free_binary(&(data));
    break;
  }
  case LIBUSB_DRV_CMD_CONTROL_TRANSFER_READ: {
    libusb_device_handle* dev_handle;
    uint8_t request_type;
    uint8_t request;
    uint16_t value;
    uint16_t index;
    uint16_t length;
    unsigned int timeout;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_uint8(c_in,&request_type);
    cbuf_get_uint8(c_in,&request);
    cbuf_get_uint16(c_in,&value);
    cbuf_get_uint16(c_in,&index);
    cbuf_get_uint16(c_in,&length);
    cbuf_get_uint(c_in,&timeout);
    libusb_drv_impl_control_transfer_read(ctx,c_out,dev_handle,request_type,request,value,index,length,timeout);
    break;
  }
  case LIBUSB_DRV_CMD_BULK_TRANSFER_WRITE: {
    libusb_device_handle* dev_handle;
    uint8_t endpoint;
    eapi_binary_t data;
    unsigned int timeout;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_uint8(c_in,&endpoint);
    cbuf_get_nbinary(c_in,&data);
    cbuf_get_uint(c_in,&timeout);
    libusb_drv_impl_bulk_transfer_write(ctx,c_out,dev_handle,endpoint,&data,timeout);
    cbuf_free_binary(&(data));
    break;
  }
  case LIBUSB_DRV_CMD_BULK_TRANSFER_READ: {
    libusb_device_handle* dev_handle;
    uint8_t endpoint;
    int length;
    unsigned int timeout;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_uint8(c_in,&endpoint);
    cbuf_get_int(c_in,&length);
    cbuf_get_uint(c_in,&timeout);
    libusb_drv_impl_bulk_transfer_read(ctx,c_out,dev_handle,endpoint,length,timeout);
    break;
  }
  case LIBUSB_DRV_CMD_INTERRUPT_TRANSFER_WRITE: {
    libusb_device_handle* dev_handle;
    uint8_t endpoint;
    eapi_binary_t data;
    unsigned int timeout;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_uint8(c_in,&endpoint);
    cbuf_get_nbinary(c_in,&data);
    cbuf_get_uint(c_in,&timeout);
    libusb_drv_impl_interrupt_transfer_write(ctx,c_out,dev_handle,endpoint,&data,timeout);
    cbuf_free_binary(&(data));
    break;
  }
  case LIBUSB_DRV_CMD_INTERRUPT_TRANSFER_READ: {
    libusb_device_handle* dev_handle;
    uint8_t endpoint;
    int length;
    unsigned int timeout;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_uint8(c_in,&endpoint);
    cbuf_get_int(c_in,&length);
    cbuf_get_uint(c_in,&timeout);
    libusb_drv_impl_interrupt_transfer_read(ctx,c_out,dev_handle,endpoint,length,timeout);
    break;
  }
  case LIBUSB_DRV_CMD_ISO_TRANSFER_WRITE: {
    libusb_device_handle* dev_handle;
    uint8_t endpoint;
    eapi_binary_t data;
    int num_iso_packets;
    unsigned int packet_size;
    unsigned int timeout;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_uint8(c_in,&endpoint);
    cbuf_get_nbinary(c_in,&data);
    cbuf_get_int(c_in,&num_iso_packets);
    cbuf_get_uint(c_in,&packet_size);
    cbuf_get_uint(c_in,&timeout);
    libusb_drv_impl_iso_transfer_write(ctx,c_out,dev_handle,endpoint,&data,num_iso_packets,packet_size,timeout);
    cbuf_free_binary(&(data));
    break;
  }
  case LIBUSB_DRV_CMD_ISO_TRANSFER_READ: {
    libusb_device_handle* dev_handle;
    uint8_t endpoint;
    int length;
    int num_iso_packets;
    unsigned int packet_size;
    unsigned int timeout;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_uint8(c_in,&endpoint);
    cbuf_get_int(c_in,&length);
    cbuf_get_int(c_in,&num_iso_packets);
    cbuf_get_uint(c_in,&packet_size);
    cbuf_get_uint(c_in,&timeout);
    libusb_drv_impl_iso_transfer_read(ctx,c_out,dev_handle,endpoint,length,num_iso_packets,packet_size,timeout);
    break;
  }
  case LIBUSB_DRV_CMD_CANCEL_TRANSFER: {
    uint32_t ref;
    cbuf_get_uint32(c_in,&ref);
    libusb_drv_impl_cancel_transfer(ctx,c_out,ref);
    break;
  }
  case LIBUSB_DRV_CMD_KERNEL_DRIVER_ACTIVE: {
    libusb_device_handle* dev_handle;
    int interface;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_int(c_in,&interface);
    libusb_drv_impl_kernel_driver_active(ctx,c_out,dev_handle,interface);
    break;
  }
  case LIBUSB_DRV_CMD_DETACH_KERNEL_DRIVER: {
    libusb_device_handle* dev_handle;
    int interface;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_int(c_in,&interface);
    libusb_drv_impl_detach_kernel_driver(ctx,c_out,dev_handle,interface);
    break;
  }
  case LIBUSB_DRV_CMD_ATTACH_KERNEL_DRIVER: {
    libusb_device_handle* dev_handle;
    int interface;
    eapi_get_pointer(ctx,c_in, (void**)&dev_handle);
    cbuf_get_int(c_in,&interface);
    libusb_drv_impl_attach_kernel_driver(ctx,c_out,dev_handle,interface);
    break;
  }
  default:
    return -1;
  }
  return 0;
}
